<span class="pull-right">
    <a href="#" class="btn btn-success">Insert</a>
    <a href="#" class="btn btn-warning">Update</a>
    <a href="#" class="btn btn-danger">Delete</a>
</span>

<h1>Audit Entity Target Association</h1>

<?php $paginator = $this->auditAssociationTargetPaginator($this->page, $this->revisionEntity, $this->joinTable); ?>

<table class="table table-striped table-hover table-bordered">
    <thead>
        <tr>
            <th colspan="4">
            <?php echo $this->paginationControl($paginator,
                'Sliding',
                'soliant-entity-audit/pagination/association-target', array('route' => 'audit/association-target'));
            ?>
            </th>
        </tr>
        <tr>
            <th>Revision</th>
            <th>Target</th>
            <th>Source</th>
            <th>Comment</th>
            <th>User</th>
        </tr>
    </thead>

    <tfoot>
        <th colspan="4">
            <?php echo $this->paginationControl($paginator,
                'Sliding',
                'soliant-entity-audit/pagination/association-target', array('route' => 'audit/page'));
            ?>
        </th>
    </tfoot>
    <tbody>
    <?php
    foreach ($paginator as $association) {
    ?>
        <tr>
            <td>
                <a href="<?=
                    $this->url('audit/revisions',
                        array(
                            'revisionId' => $revisionEntity->getRevision()->getId()
                        )
                    );
                ?>">

                    <?= $this->escapeHtml($revisionEntity->getRevision()->getId());?>
                    @ <?php echo $this->AuditDateTimeFormatter($revisionEntity->getRevision()->getTimestamp()); ?>

                </a>
            </td>

            <td>
                <?= $this->auditRevisionEntityLink($association->getTargetRevisionEntity()); ?>
            </td>

            <td>
                <?= $this->auditRevisionEntityLink($association->getSourceRevisionEntity()); ?>
            </td>

            <td><?= $this->escapeHtml($revisionEntity->getRevision()->getComment()); ?></td>

            <td>
                <a href="<?php
                    if ($revisionEntity->getRevision()->getUser()) {
                        echo $this->url('audit/user', array('userId' => $revisionEntity->getRevision()->getUser()->getId()));
                    } else {
                        echo $this->url('audit/user', array('userId' => '0'));
                    }
                ?>" class="btn btn-default">
                    <?php
                        if ($revisionEntity->getRevision()->getUser()) {
                            echo $this->gravatar($revisionEntity->getRevision()->getUser()->getEmail(), array('img_size' => 24));
                            echo ' ';
                            echo $this->escapeHtml($revisionEntity->getRevision()->getUser()->getDisplayName());
                        } else {
                            echo $this->gravatar('anonymous@unknown.net', array('img_size' => 24));
                            echo ' Anonymous';
                        }
                    ?>
                </a>
            </td>
        </tr>
        <?php
        }
        ?>
    </tbody>
</table>
