<?php
    use Doctrine\ORM\Mapping\ClassMetadataInfo;
?>

<h1>Audit Revision Entity</h1>

<table class="table table-striped table-hover table-bordered">
    <thead>
        <tr>
            <th>Revision</th>
            <th>Entity</th>
            <th>Comment</th>
            <th>User</th>
        </tr>
    </thead>

    <tbody>
        <tr>
            <td>
                <a href="<?=
                    $this->url('audit/revisions',
                        array(
                            'revisionId' => $this->revisionEntity->getRevision()->getId()
                        )
                    );
                ?>">

                    <?= $this->revisionEntity->getRevision()->getId(); ?>

                    @ <?php echo $this->AuditDateTimeFormatter($revisionEntity->getRevision()->getTimestamp()); ?>
                </a>

            </td>

            <td>
                <?= $this->auditRevisionEntityLink($revisionEntity); ?>
            </td>

            <td><?= $this->escapeHtml($this->revisionEntity->getRevision()->getComment()); ?></td>

            <td>
                <a href="<?php
                    if ($this->revisionEntity->getRevision()->getUser()) {
                        echo $this->url('audit/user', array('userId' => $this->revisionEntity->getRevision()->getUser()->getId()));
                    } else {
                        echo $this->url('audit/user', array('userId' => '0'));
                    }
                ?>" class="btn btn-default">
                    <?php
                        if ($this->revisionEntity->getRevision()->getUser()) {
                            echo $this->gravatar($this->revisionEntity->getRevision()->getUser()->getEmail(), array('img_size' => 24));
                            echo ' ';
                            echo $this->escapeHtml($this->revisionEntity->getRevision()->getUser()->getDisplayName());
                        } else {
                            echo $this->gravatar('anonymous@unknown.net', array('img_size' => 24));
                            echo ' Anonymous';
                        }
                    ?>
                </a>
            </td>
        </tr>
    </tbody>
</table>

<table class="table table-striped table-hover table-bordered ">
    <caption>
        Audited Entity Values
    </caption>
    <thead>
        <tr>
            <th>Field</th>
            <th>Value</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($this->auditService()->getEntityValues($this->revisionEntity->getAuditEntity()) as $field => $value) { ?>
            <tr>
                <td><?php  echo $this->escapeHtml($field); ?></td>
                <td>
                <?php

                    // Is this an association?
                    if (in_array($field, array_keys($this->auditService()->getEntityAssociations($this->revisionEntity->getAuditEntity())))) {
                        $associationRevisionEntity = $this->auditService()->getAssociationRevisionEntity($this->revisionEntity->getAuditEntity(), $field, $value);

                        if ($associationRevisionEntity) {
                            echo $this->auditRevisionEntityLink($associationRevisionEntity);
                        }
                    }
                    ?>
                </td>
            </tr>
        <?php
            }
        ?>

        <?php
        if ($this->auditService()->getEntityAssociations($this->revisionEntity->getAuditEntity())) {
        ?>
            <tr>
                <th>Associations</th>
                <th>Link</th>
            </tr>

            <?php
                foreach($this->auditService()->getEntityAssociations($this->revisionEntity->getAuditEntity()) as $field => $value) {
            ?>
                    <?php

                    switch ($value['type']) {
                        case ClassMetadataInfo::ONE_TO_ONE: # 1
                            echo 'one to one';
                            break;

                        case ClassMetadataInfo::MANY_TO_ONE: # 2
                            // Handled in field listing
                            break;

                        case ClassMetadataInfo::ONE_TO_MANY: # 4
                            // Verify an audit class exists for this field
                            if (!class_exists('SoliantEntityAudit\\Entity\\' . str_replace('\\', '_', $value['targetEntity'])))
                                continue;


                            ?>
                            <tr>
                                <td><?php  echo $this->escapeHtml($field); ?></td>
                                <td>


                            <a class="btn btn-<?php
                                switch ($this->revisionEntity->getRevisionType()) {
                                    case 'INS':
                                        echo 'success';
                                        break;
                                    case 'UPD':
                                        echo 'warning';
                                        break;
                                    case 'DEL':
                                        echo 'danger';
                                        break;
                                    default:
                                        echo 'info';
                                }
                            ?>"

                            <?php

                                $moduleOptions = \SoliantEntityAudit\Module::getModuleOptions();
                                $joinClasses = $moduleOptions->getJoinClasses();
                                foreach ($joinClasses as $join) {
                                    if ($join['sourceEntity'] == $value['targetEntity'])
                                        continue;
                                }

                            ?>
                                href="<?=
                                    $this->url(
                                        'audit/one-to-many',
                                        array(
                                            'revisionEntityId' => $this->revisionEntity->getId(),
                                            'joinTable' => $value['targetEntity'],
                                            'mappedBy' => $value['mappedBy'],
                                            'page' => 0,
                                        )
                                    );?>"
                                >

                                <?= $this->escapeHtml($value['targetEntity']); ?>
                            </a>
                        </td>
                    </tr>

                            <?php

                            break;

                        case ClassMetadataInfo::MANY_TO_MANY: #8
                            ?>

                            <tr>
                                <td><?php  echo $this->escapeHtml($field); ?></td>
                                <td>

                            <a class="btn btn-<?php
                                switch ($this->revisionEntity->getRevisionType()) {
                                    case 'INS':
                                        echo 'success';
                                        break;
                                    case 'UPD':
                                        echo 'warning';
                                        break;
                                    case 'DEL':
                                        echo 'danger';
                                        break;
                                    default:
                                        echo 'info';
                                }
                            ?>"

                            <?php
                            if (!isset($value['joinTable'])) {
                                // Handle inverse

                                // Find join table association where target and source are inverse of this association
                                // which will have the join table name
                                $moduleOptions = \SoliantEntityAudit\Module::getModuleOptions();
                                $joinClasses = $moduleOptions->getJoinClasses();
                                foreach ($joinClasses as $join) {
                                    if ($join['sourceEntity'] == $value['targetEntity'])
                                        continue;
                                }

                            ?>
                                href="<?=
                                    $this->url(
                                        'audit/association-source',
                                        array(
                                            'revisionEntityId' => $this->revisionEntity->getId(),
                                            'joinTable' => $join['joinTable']['name'],
                                            'page' => 0,
                                        )
                                    );?>"
                                >

                                <?= $this->escapeHtml($join['joinTable']['name']); ?>
                                <br>
                                (<?= $this->escapeHtml($join['sourceEntity']); ?>)
                            <?php
                            } else {
                                // Handle source
                                ?>
                                href="<?=
                                    $this->url(
                                        'audit/association-target',
                                        array(
                                            'revisionEntityId' => $this->revisionEntity->getId(),
                                            'joinTable' => $value['joinTable']['name'],
                                            'page' => 0,
                                        )
                                    );?>"
                                >

                                <?= $this->escapeHtml($value['joinTable']['name']); ?>
                                <br>
                                (<?= $this->escapeHtml($value['targetEntity']); ?>)
                            <?php
                            }
                            ?>
                            </a>
                        </td>
                    </tr>
                                <?php
                            break;

                        default:
                            break;
                    }

                ?>
            <?php
            }
        }
        ?>
    </tbody>
</table>


<form action="<?=
    $this->url('audit/compare',
        array(
        )
    );
    ?>" method="post">

<?php
    $first = true;
    $oldSet = false;
    $paginator = $this->auditRevisionEntityPaginator($page, $this->revisionEntity->getAuditEntity());
?>

<table class="table table-striped table-hover table-bordered ">
    <caption>
        Compare Revision Entities
    </caption>
    <thead>
        <tr>
            <th colspan="6">
                <?=
                $this->paginationControl($paginator,
                    'Sliding',
                    'soliant-entity-audit/pagination/revision-entity',
                    array(
                        'route' => 'audit/revision-entity',
                        'revisionEntityId' => $this->revisionEntity->getId(),
                    )
                ); ?>
            </th>

        </tr>
        <tr>
            <th>Revision</th>
            <th>Entity</th>
            <th>Comment</th>
            <th>User</th>
            <th>Old</th>
            <th>New</th>
        </tr>
    </thead>
    <tfoot>
        <tr>
            <th colspan="6">
                <?=
                $this->paginationControl($paginator,
                    'Sliding',
                    'soliant-entity-audit/pagination/revision-entity',
                    array(
                        'route' => 'audit/revision-entity',
                        'revisionEntityId' => $this->revisionEntity->getId(),
                    )
                ); ?>
            </th>

        </tr>
    </tfoot>
    <tbody>
        <?php
        foreach ($paginator as $rev) {
        ?>
            <tr>
                <td>
                    <a href="<?=
                        $this->url('audit/revisions',
                            array(
                                'revisionId' => $rev->getRevision()->getId()
                            )
                        );
                    ?>">

                        <?= $rev->getRevision()->getId(); ?>
                        @ <?php echo $this->AuditDateTimeFormatter($rev->getRevision()->getTimestamp()); ?>

                    </a>
                </td>

                <td>
                    <?= $this->auditRevisionEntityLink($rev); ?>
                </td>

                <td><?= $this->escapeHtml($rev->getRevision()->getComment()); ?></td>

                <td>
                    <a href="<?php
                        if ($rev->getRevision()->getUser()) {
                            echo $this->url('audit/user', array('userId' => $rev->getRevision()->getUser()->getId()));
                        } else {
                            echo $this->url('audit/user', array('userId' => '0'));
                        }
                    ?>" class="btn btn-default">
                        <?php
                            if ($rev->getRevision()->getUser()) {
                                echo $this->gravatar($rev->getRevision()->getUser()->getEmail(), array('img_size' => 24));
                                echo ' ';
                                echo $this->escapeHtml($rev->getRevision()->getUser()->getDisplayName());
                            } else {
                                echo $this->gravatar('anonymous@unknown.net', array('img_size' => 24));
                                echo ' Anonymous';
                            }
                        ?>
                    </a>
                </td>

                <td>
                    <input type="radio" name="revisionEntityId_old" value="<?php  echo $this->escapeHtml($rev->getId()); ?>"
                        <?php
                        if (sizeof($paginator) == 1 or ($rev == $this->revisionEntity and !$first) or (!$oldSet and !$first)) {
                            echo 'checked="checked"';
                            $oldSet = true;
                        }
                        ?> />
                </td>
                <td>
                    <input type="radio" name="revisionEntityId_new" value="<?php  echo $this->escapeHtml($rev->getId()); ?>"
                        <?php
                        if ($first) {
                            echo 'checked="checked"';
                            $first = false;
                        }
                        ?> />
                </td>
            </tr>
            <?php
            }
            ?>
    </tbody>
</table>

    <input type="submit" class="btn btn-primary" value="Compare revisions" />

</form>

    <a href="<?=
            $this->url(
                'audit/entity',
                array(
                    'entityClass' => $this->revisionEntity->getAuditEntity()->getAuditedEntityClass(),
                )
            );?>
    " class="btn btn-primary">All Revisons for <?= $this->escapeHtml($this->revisionEntity->getAuditEntity()->getAuditedEntityClass()); ?></a>
