<?php
if ($user) {
    $userId = $user->getId();
?>
    <h1>Audit by user <?= $this->escapeHtml($user->getDisplayName()); ?></h1>
<?php
} else {
    $userId = null;
?>
<h1>Audit Anonymous Revisions</h1>
<?php
}
?>
<?php $paginator = $this->auditRevisionPaginator($this->page, array('user' => $userId)); ?>

<table class="table table-striped table-hover table-bordered">
    <thead>
        <tr>
            <th colspan="4">
            <?php echo $this->paginationControl($paginator,
                'Sliding',
                'soliant-entity-audit/pagination/revision', array('route' => 'audit/page'));
            ?>
            </th>
        </tr>
        <tr>
            <th>Revision</th>
            <th>Entity</th>
            <th>Comment</th>
            <th>User</th>
        </tr>
    </thead>

    <tfoot>
        <th colspan="4">
            <?php echo $this->paginationControl($paginator,
                'Sliding',
                'soliant-entity-audit/pagination/revision', array('route' => 'audit/page'));
            ?>
        </th>
    </tfoot>
    <tbody>
    <?php
    foreach ($paginator as $revision) {
    ?>
        <tr>
            <td>
                <a href="<?=
                    $this->url('audit/revisions',
                        array(
                            'revisionId' => $revision->getId()
                        )
                    );
                ?>">

                    <?= $this->escapeHtml($revision->getId());?>
                    @ <?php echo $this->AuditDateTimeFormatter($revision->getTimestamp()); ?>

                </a>
            </td>

            <td>
            <?php
            foreach ($revision->getRevisionEntities() as $revisionEntity) {
            ?>
                <div>
                    <?= $this->auditRevisionEntityLink($revisionEntity); ?>
                </div>
            <?php
            }
            ?>
            </td>

            <td><?= $this->escapeHtml($revision->getComment()); ?></td>

            <td>
                <a href="<?php
                    if ($revision->getUser()) {
                        echo $this->url('audit/user', array('userId' => $revision->getUser()->getId()));
                    } else {
                        echo $this->url('audit/user', array('userId' => '0'));
                    }
                ?>" class="btn btn-default">
                    <?php
                        if ($revision->getUser()) {
                            echo $this->gravatar($revision->getUser()->getEmail(), array('img_size' => 24));
                            echo ' ';
                            echo $this->escapeHtml($revision->getUser()->getDisplayName());
                        } else {
                            echo $this->gravatar('anonymous@unknown.net', array('img_size' => 24));
                            echo ' Anonymous';
                        }
                    ?>
                </a>
            </td>
        </tr>
    <?php
    }
    ?>
    </tbody>
</table>
