<div style="text-align: left;" class="btn btn-<?php
    switch ($this->revisionEntity->getRevisionType()) {
        case 'INS':
            echo 'success';
            break;
        case 'UPD':
            echo 'warning';
            break;
        case 'DEL':
            echo 'danger';
            break;
        default:
            echo 'info';
    }
?>">
    <?php
    if ($options = $this->auditEntityOptions($this->revisionEntity->getTargetEntityClass())) {
        $routeOptions = array_merge($options['defaults'], $this->revisionEntity->getEntityKeys());
    ?>
        <a class="btn btn-info"  href="<?=
            $this->url($options['route'], $routeOptions);
        ?>"><i class="icon-list"></i></a>
    <?php
    }
    ?>
    <a class="btn btn-<?php
    switch ($this->revisionEntity->getRevisionType()) {
        case 'INS':
            echo 'success';
            break;
        case 'UPD':
            echo 'warning';
            break;
        case 'DEL':
            echo 'danger';
            break;
        default:
            echo 'info';
    }
?>"
    href="<?=
        $this->url(
            'audit/revision-entity',
            array(
                'revisionEntityId' => $this->revisionEntity->getId(),
            )
        );?>"
    >

    <?= $this->escapeHtml(substr($this->revisionEntity->getAuditEntity()->getAuditedEntityClass(), strrpos($this->revisionEntity->getAuditEntity()->getAuditedEntityClass(), '\\') + 1)); ?>:

    <?php
    if ($this->revisionEntity->getTitle()) {
    ?>
        <?= $this->escapeHtml($this->revisionEntity->getTitle()); ?>
        <br>
    <?php
    }
    ?>

<!--   (<?= $this->revisionEntity->getId(); ?>) -->


    <div class="entityKeys">
        <?php
        $rows = array();
        foreach($revisionEntity->getEntityKeys() as $key => $value) {
            $rows[] = $this->escapeHtml($key) . ' => ' . $this->escapeHtml($value);
        }
        echo implode(', ', $rows);
        ?>
    </div>
</a>
</div>

